### Check if it is okay
GET http://127.0.0.1:5000


### Creating a user
POST http://127.0.0.1:5000/create-user HTTP/1.1
Content-Type: application/json

{
    "username":"jubayr",
    "password":"mesrikatRusty@21"
}

### Login

POST http://127.0.0.1:5000/login HTTP/1.1
Content-Type: application/json

{
    "username":"jubayr",
    "password":"mesrikatRusty@21"
}

### Check 
GET http://127.0.0.1:5000/check HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY4MTkyMTMwOCwianRpIjoiNWNhN2E5YTQtMDlkOS00M2ExLTg3ODgtZjhiNmU4OTE3YzMzIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6Imp1YmF5ciIsIm5iZiI6MTY4MTkyMTMwOCwiZXhwIjoxNjgxOTI0OTA4fQ.woSS7s730xsvklS_Dbe6YRec6MzVW54RpxjrF5WMTi0

### Refresh token

POST http://127.0.0.1:5000/refresh HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY4MTkwMDk2MywianRpIjoiNGYwNmRhMGUtYzM5YS00Nzk1LTkyNzEtMjgwMWE1ZTQ3NDFkIiwidHlwZSI6InJlZnJlc2giLCJzdWIiOiJqdWJheXIiLCJuYmYiOjE2ODE5MDA5NjMsImV4cCI6MTY4NDQ5Mjk2M30.yiv5rjT9c-cSGGUcWWzWFuwglyquyt0-bDbfYvr2fqE

{
    "refresh_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY4MTkwMDY5NCwianRpIjoiM2M0ZDBmM2QtNjJmZS00NzVkLWJiNzUtMGUzYjU2Zjg4YjU3IiwidHlwZSI6InJlZnJlc2giLCJzdWIiOiJqdWJheXIiLCJuYmYiOjE2ODE5MDA2OTQsImV4cCI6MTY4NDQ5MjY5NH0.jGzUxTWD9DdzQx_-uAOGJhAcE8dUQ3Rebba9h9IMqaw"
}
